### ISSUE TITLE
Cannot export model

### ISSUE THREAD

**Issue by nvdl** [makehumancommunity/makehuman_python3#27]
The export raises an exception at the following line:

https://github.com/makehumancommunity/makehuman_python3/blob/master/makehuman/core/module3d.py#L311

I have tried different formats but the error is the same.

Log:
Traceback (most recent call last):
  File "./core/events3d.py", line 211, in callEvent
    method(event)
  File "./apps/gui/guiexport.py", line 112, in onFileSelected
    exporter.export(gui3d.app.selectedHuman, filename)
  File "plugins/9_export_stl/__init__.py", line 78, in export
    mh2stl.exportStlAscii(filename("stl"), cfg)
  File "plugins/9_export_stl/mh2stl.py", line 80, in exportStlAscii
    meshes = [o.mesh.clone(1,True) for o in objects]
  File "./apps/catmull_clark_subdivision.py", line 485, in clone
    otherSeed = self.parent.clone(scale, filterMaskedVerts)
  File "./core/module3d.py", line 160, in clone
    self.filterMaskedVerts(other, update=False)
  File "./core/module3d.py", line 311, in filterMaskedVerts
    inverse_uv_idx[uv_idx] = np.arange(self.texco.shape[0], dtype=np.int32)
ValueError: shape mismatch: value array of shape (21334,) could not be broadcast to indexing result of shape (14517,)

[2017-10-24 01:18:01,126] log.py->message():133 -- MESSAGE -- Initialized logging
[2017-10-24 01:18:01,134] log.py->debug():112 -- DEBUG -- VERSION: 1.1.0
[2017-10-24 01:18:01,134] log.py->debug():112 -- DEBUG -- HG REVISION: r? (UNKNOWN) [none found]
[2017-10-24 01:18:01,135] log.py->debug():112 -- DEBUG -- SHORT VERSION: v1.1.0
[2017-10-24 01:18:01,135] log.py->debug():112 -- DEBUG -- BASEMESH VERSION: hm08
[2017-10-24 01:18:01,135] log.py->debug():112 -- DEBUG -- IS BUILT (FROZEN): No
[2017-10-24 01:18:01,135] log.py->debug():112 -- DEBUG -- IS RELEASE VERSION: Yes
[2017-10-24 01:18:01,135] log.py->debug():112 -- DEBUG -- WORKING DIRECTORY: /usr/share/makehuman
[2017-10-24 01:18:01,136] log.py->debug():112 -- DEBUG -- HOME LOCATION: /home/xxx
[2017-10-24 01:18:01,136] log.py->debug():112 -- DEBUG -- PYTHON PATH: ./:./lib:./apps:./shared:./apps/gui:./core:/usr/share/makehuman:/usr/lib/python2.7:/usr/lib/python2.7/plat-x86_64-linux-gnu:/usr/lib/python2.7/lib-tk:/usr/lib/python2.7/lib-old:/usr/lib/python2.7/lib-dynload:/usr/local/lib/python2.7/dist-packages:/usr/lib/python2.7/dist-packages:/usr/lib/python2.7/dist-packages/gtk-2.0
[2017-10-24 01:18:01,136] log.py->debug():112 -- DEBUG -- DLL PATH: /usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
[2017-10-24 01:18:01,136] log.py->debug():112 -- DEBUG -- SYS.VERSION: 2.7.13 (default, Jan 19 2017, 14:48:08)  [GCC 6.3.0 20170118]
[2017-10-24 01:18:01,137] log.py->debug():112 -- DEBUG -- SYS.PLATFORM: linux2
[2017-10-24 01:18:01,137] log.py->debug():112 -- DEBUG -- SYS.EXECUTABLE: /usr/bin/python
[2017-10-24 01:18:01,139] log.py->debug():112 -- DEBUG -- PLATFORM.MACHINE: x86_64
[2017-10-24 01:18:01,139] log.py->debug():112 -- DEBUG -- PLATFORM.PROCESSOR: 
[2017-10-24 01:18:01,139] log.py->debug():112 -- DEBUG -- PLATFORM.UNAME.RELEASE: 4.9.0-4-amd64
[2017-10-24 01:18:01,140] log.py->debug():112 -- DEBUG -- PLATFORM.LINUX_DISTRIBUTION: debian 9.2 
[2017-10-24 01:18:01,284] log.py->debug():112 -- DEBUG -- NUMPY.VERSION: 1.13.3
[2017-10-24 01:18:01,358] acceleratesupport.py-><module>():17 -- MESSAGE -- No OpenGL_accelerate module loaded: No module named OpenGL_accelerate
[2017-10-24 01:18:01,848] log.py->debug():112 -- DEBUG -- PYQT.VERSION: 4.8.7
[2017-10-24 01:18:01,860] log.py->debug():112 -- DEBUG -- PYQT.JPG_SUPPORT: supported
[2017-10-24 01:18:01,860] log.py->debug():112 -- DEBUG -- PYQT.SVG_SUPPORT: supported
[2017-10-24 01:18:01,862] log.py->debug():112 -- DEBUG -- QT.PLUGIN_PATH: /usr/lib/x86_64-linux-gnu/qt4/plugins:/usr/bin
[2017-10-24 01:18:01,862] log.py->debug():112 -- DEBUG -- QT.PLUGIN_PATH_ENV: 
[2017-10-24 01:18:01,862] log.py->debug():112 -- DEBUG -- QT.CONF: NOT PRESENT
[2017-10-24 01:18:01,936] log.py->debug():112 -- DEBUG -- PYOPENGL.VERSION: 3.1.0
[2017-10-24 01:18:01,936] log.py->debug():112 -- DEBUG -- GL.VENDOR: Intel Open Source Technology Center
[2017-10-24 01:18:01,936] log.py->debug():112 -- DEBUG -- GL.RENDERER: Mesa DRI Intel(R) Haswell Mobile 
[2017-10-24 01:18:01,937] log.py->debug():112 -- DEBUG -- GL.VERSION: 3.0 Mesa 13.0.6
[2017-10-24 01:18:01,937] log.py->debug():112 -- DEBUG -- GLSL.VERSION: 1.30
[2017-10-24 01:18:01,940] log.py->debug():112 -- DEBUG -- GL.EXTENSION: GL_ARB_multisample enabled (4x samples)
[2017-10-24 01:18:01,941] log.py->debug():112 -- DEBUG -- Creating new texture for image data/textures/texture_notfound.png.
[2017-10-24 01:18:01,946] log.py->debug():112 -- DEBUG -- GL.EXTENSION: GL_ARB_texture_non_power_of_two enabled
[2017-10-24 01:18:01,947] log.py->debug():112 -- DEBUG -- initTexture: 256, 256, False

**Comment by joepal1976** [comment]
This is http://bugtracker.makehumancommunity.org/issues/1184 which has a fix https://bitbucket.org/MakeHuman/makehuman/pull-requests/33/bug-1184-fix/diff

I'm going to merge and port this as soon as I have a few free hours to make sure it works with other versions of numpy too. However, since it's a very simple fix, it's possible you could simply copy/paste it to your local repo for now. 

I'll leave the github issue open here until I have ported the fix.

**Comment by nvdl** [comment]
Thanks. Could not find this patch while searching.
