### ISSUE TITLE
Type error on startup

### ISSUE THREAD

**Issue by rwbaer** [makehumancommunity/makehuman_python3#3]
WARNING:root:Exception during event onStart
Traceback (most recent call last):
  File "./core\events3d.py", line 219, in callEvent
    method(event)
  File "./core\mhmain.py", line 807, in onStart
    self.startupSequence()
  File "./core\mhmain.py", line 729, in startupSequence
    self.loadHuman()
  File "./core\mhmain.py", line 384, in loadHuman
    self.selectedHuman = self.addObject(human.Human(files3d.loadMesh(mh.getSysDataPath("3dobjs/base.obj"), maxFaces = 5)))
  File "./apps\human.py", line 70, in __init__
    self.maskFaces()
  File "./apps\human.py", line 233, in maskFaces
    if g.name.startswith('joint-') or g.name.startswith('helper-'):
TypeError: startswith first arg must be bytes or a tuple of bytes, not str

**Comment by rwbaer** [comment]
This is fixed
