### ISSUE TITLE
debugdump.py error

### ISSUE THREAD

**Issue by rwbaer** [makehumancommunity/makehuman_python3#4]
Traceback (most recent call last):
  File "C:\Users\Rob Baer\git\makehuman_python3\makehuman\makehuman.py", line 415, in debug_dump
    debugdump.dump.reset()
  File "./lib\debugdump.py", line 119, in reset
    self.write("PLATFORM.WIN32_VER: %s", string.join(platform.win32_ver()," "))
AttributeError: 'module' object has no attribute 'join'
MESSAGE:OpenGL.acceleratesupport:No OpenGL_accelerate module loaded: No module named 'OpenGL_accelerate'

**Comment by rwbaer** [comment]
openGL versioning now reports to logs
