### ISSUE TITLE
Shoe assets produce TypeError: the JSON object must be str, not 'bytes'

### ISSUE THREAD

**Issue by rwbaer** [makehumancommunity/makehuman_python3#5]
TypeErrors seem to all happen together starting with shoe01.json and continuing through shoes06.json - then stop.   What is different about shoes?

Somehow this relates to the presence of this line 38 in shoes01.mclo:
**vertexboneweights_file shoes01.mhw**

Note:  This happens after fixing line 233 in human.py to be byte string which allowed compile_proxies.py to at least start working. Clearly type issues to work out.

...
[23% done] converted proxy data\clothes\male_elegantsuit01\male_elegantsuit01.mhclo
[25% done] converted proxy data\clothes\male_worksuit01\male_worksuit01.mhclo
Could not load proxy file data\clothes\shoes01\shoes01.mhclo.
Traceback (most recent call last):
  File "C:\MHPY3-GIT\makehuman\compile_proxies.py", line 71, in compileProxy
    proxy_ = proxy.loadTextProxy(human, path, type=None)
  File "./shared\proxy.py", line 489, in loadTextProxy
    proxy.vertexBoneWeights = VertexBoneWeights.fromFile(proxy.vertexBoneWeights_file)
  File "./shared\animation.py", line 527, in fromFile
    weightsData = json.load(open(filename, 'rb'), object_pairs_hook=OrderedDict)
  File "C:\WinPython-64bit-3.4.4.1\python-3.4.4.amd64\lib\json\__init__.py", line 268, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "C:\WinPython-64bit-3.4.4.1\python-3.4.4.amd64\lib\json\__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'
[26% done] converted proxy data\clothes\shoes01\shoes01.mhclo
Could not load proxy file data\clothes\shoes02\shoes02.mhclo.
Traceback (most recent call last):
  File "C:\MHPY3-GIT\makehuman\compile_proxies.py", line 71, in compileProxy
    proxy_ = proxy.loadTextProxy(human, path, type=None)
  File "./shared\proxy.py", line 489, in loadTextProxy
    proxy.vertexBoneWeights = VertexBoneWeights.fromFile(proxy.vertexBoneWeights_file)
  File "./shared\animation.py", line 527, in fromFile
    weightsData = json.load(open(filename, 'rb'), object_pairs_hook=OrderedDict)
  File "C:\WinPython-64bit-3.4.4.1\python-3.4.4.amd64\lib\json\__init__.py", line 268, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "C:\WinPython-64bit-3.4.4.1\python-3.4.4.amd64\lib\json\__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'
[28% done] converted proxy data\clothes\shoes02\shoes02.mhclo
Could not load proxy file data\clothes\shoes03\shoes03.mhclo.
Traceback (most recent call last):
  File "C:\MHPY3-GIT\makehuman\compile_proxies.py", line 71, in compileProxy
    proxy_ = proxy.loadTextProxy(human, path, type=None)
  File "./shared\proxy.py", line 489, in loadTextProxy
    proxy.vertexBoneWeights = VertexBoneWeights.fromFile(proxy.vertexBoneWeights_file)
  File "./shared\animation.py", line 527, in fromFile
    weightsData = json.load(open(filename, 'rb'), object_pairs_hook=OrderedDict)
  File "C:\WinPython-64bit-3.4.4.1\python-3.4.4.amd64\lib\json\__init__.py", line 268, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "C:\WinPython-64bit-3.4.4.1\python-3.4.4.amd64\lib\json\__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'
[30% done] converted proxy data\clothes\shoes03\shoes03.mhclo
Could not load proxy file data\clothes\shoes04\shoes04.mhclo.
Traceback (most recent call last):
  File "C:\MHPY3-GIT\makehuman\compile_proxies.py", line 71, in compileProxy
    proxy_ = proxy.loadTextProxy(human, path, type=None)
  File "./shared\proxy.py", line 489, in loadTextProxy
    proxy.vertexBoneWeights = VertexBoneWeights.fromFile(proxy.vertexBoneWeights_file)
  File "./shared\animation.py", line 527, in fromFile
    weightsData = json.load(open(filename, 'rb'), object_pairs_hook=OrderedDict)
  File "C:\WinPython-64bit-3.4.4.1\python-3.4.4.amd64\lib\json\__init__.py", line 268, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "C:\WinPython-64bit-3.4.4.1\python-3.4.4.amd64\lib\json\__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'
[32% done] converted proxy data\clothes\shoes04\shoes04.mhclo
Could not load proxy file data\clothes\shoes05\shoes05.mhclo.
Traceback (most recent call last):
  File "C:\MHPY3-GIT\makehuman\compile_proxies.py", line 71, in compileProxy
    proxy_ = proxy.loadTextProxy(human, path, type=None)
  File "./shared\proxy.py", line 489, in loadTextProxy
    proxy.vertexBoneWeights = VertexBoneWeights.fromFile(proxy.vertexBoneWeights_file)
  File "./shared\animation.py", line 527, in fromFile
    weightsData = json.load(open(filename, 'rb'), object_pairs_hook=OrderedDict)
  File "C:\WinPython-64bit-3.4.4.1\python-3.4.4.amd64\lib\json\__init__.py", line 268, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "C:\WinPython-64bit-3.4.4.1\python-3.4.4.amd64\lib\json\__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'
[33% done] converted proxy data\clothes\shoes05\shoes05.mhclo
Could not load proxy file data\clothes\shoes06\shoes06.mhclo.
Traceback (most recent call last):
  File "C:\MHPY3-GIT\makehuman\compile_proxies.py", line 71, in compileProxy
    proxy_ = proxy.loadTextProxy(human, path, type=None)
  File "./shared\proxy.py", line 489, in loadTextProxy
    proxy.vertexBoneWeights = VertexBoneWeights.fromFile(proxy.vertexBoneWeights_file)
  File "./shared\animation.py", line 527, in fromFile
    weightsData = json.load(open(filename, 'rb'), object_pairs_hook=OrderedDict)
  File "C:\WinPython-64bit-3.4.4.1\python-3.4.4.amd64\lib\json\__init__.py", line 268, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "C:\WinPython-64bit-3.4.4.1\python-3.4.4.amd64\lib\json\__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'
[35% done] converted proxy data\clothes\shoes06\shoes06.mhclo
[37% done] converted proxy data\eyebrows\eyebrow001\eyebrow001.mhclo
...:

**Comment by rwbaer** [comment]
This seems fixed by using text rather than binary mode to open json.open( ,'r') == json.open( ,'rt') rather than json.open( ,'r'b)   humanmodifier.py and guimodifies.py were targets for this fix.  The shoes assets now work because there is access to shoesXX.mhw files.
